filter:
    excluded_paths:
        - 'docs/*'
tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR12
checks:
    php: true
build:
    environment:
        php:
            version: 7.1
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
    dependencies:
        before:
            - composer require phpunit/phpunit:^7.0 --dev
    tests:
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover