<?php

namespace Povs\ListerBundle\Type\ListType;

use Povs\ListerBundle\View\ListView;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @author Povilas Margaiatis <p.margaitis@gmail.com>
 */
interface ListTypeInterface
{
    /**
     * @param array $config type config
     *
     * @return mixed
     */
    public function setConfig(array $config);

    /**
     * @param int|null $currentPage current page from request
     *
     * @return int
     */
    public function getCurrentPage(?int $currentPage): int;

    /**
     * @param int|null $length length from request
     *
     * @return int rows length per page.
     */
    public function getLength(?int $length): int;

    /**
     * Configures type settings
     *
     * @param OptionsResolver $optionsResolver
     */
    public function configureSettings(OptionsResolver $optionsResolver): void;

    /**
     * Configures type options
     *
     * @param OptionsResolver $optionsResolver
     */
    public function configureOptions(OptionsResolver $optionsResolver): void;

    /**
     * @param ListView $listView
     * @param array    $options  passed via ListerInterface::generateResponse
     *
     * @return Response
     */
    public function generateResponse(ListView $listView, array $options): Response;

    /**
     * @param ListView $listView
     * @param array    $options  passed via ListerInterface::generateData
     *
     * @return mixed   data generated by type
     */
    public function generateData(ListView $listView, array $options);
}
